name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v6

      - name: java-setup
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: zulu

      - name: compile
        run: |
          chmod +x gradlew
          ./gradlew clean shadowJar